### ISSUE TITLE
npm dependency

### ISSUE THREAD

**Issue by klzns** [firstdoit/connect-tryfiles#2]
I've got this warning while installing:

``` sh
npm WARN engine connect-tryfiles@0.2.1: wanted: {"node":"0.10.x","npm":"1.2.x"} (current: {"node":"0.10.26","npm":"2.7.0"})
npm WARN engine connect-http-please@0.1.1: wanted: {"node":"0.10.x","npm":"1.2.x"} (current: {"node":"0.10.26","npm":"2.7.0"})
```

Does it really need npm to be in version 1?

**Comment by vibegui** [comment]
Nope, this was (unfortunately) automatically generated by the npm init.
However, I deprecated this package so I won't solve this, as it's only a (rather common) warning.
